# Bailey Korfhage
## Individual Project 2
## Version 1
## DS-160-01

In [1]:
import numpy as np

In [2]:
list1=[10,20,30,40]
array1=np.array(list1)

In [3]:
array1.resize(2,2)
array1

array([[10, 20],
       [30, 40]])

In [4]:
array1**2

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [5]:
array1+100

array([[110, 120],
       [130, 140]])

In [6]:
array1*5

array([[ 50, 100],
       [150, 200]])

In [7]:
np.sqrt(array1)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [8]:
array2=np.arange(3,28,3)
array2.resize((3,3))
array2

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [9]:
array3=np.linspace(10,20,9)
array3.resize((3,3))
array3

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [10]:
array4=array2*array3
array4

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

In [11]:
process1=np.load('process1.npy')
process2=np.load('process2.npy')
process3=np.load('process3.npy')
process4=np.load('process4.npy')
process5=np.load('process5.npy')

In [12]:
print(process1)
print(process2)
print(process3)
print(process4)
print(process5)

[[52 12 81  0 58]]
[[96  4 61 16 43]]
[[38 96 45 17 58]]
[[97 21 22 25  6]]
[[77  6 19  2 74]]


In [13]:
array5=np.concatenate([process1,process2,process3,process4,process5])
array5

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [14]:
array5.mean(axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])